import { ThingKind, ThingType } from '@/wad/constants/ThingTypes';

export const DOOM_THING_MAP: Record<string, ThingType> = {
  PLAYER1_START: {
    id: 1,
    radius: 16,
    sprite: 'PLAY',
    description: 'Player 1 start',
    kind: ThingKind.Player,
  },
  PLAYER2_START: {
    id: 2,
    radius: 16,
    sprite: 'PLAY',
    description: 'Player 2 start',
    kind: ThingKind.Player,
  },
  PLAYER3_START: {
    id: 3,
    radius: 16,
    sprite: 'PLAY',
    description: 'Player 3 start',
    kind: ThingKind.Player,
  },
  PLAYER4_START: {
    id: 4,
    radius: 16,
    sprite: 'PLAY',
    description: 'Player 4 start',
    kind: ThingKind.Player,
  },
  BLUE_KEYCARD: {
    id: 5,
    radius: 20,
    sprite: 'BKEY',
    sequence: 'AB',
    description: 'Blue keycard',
    kind: ThingKind.Key,
  },
  YELLOW_KEYCARD: {
    id: 6,
    radius: 20,
    sprite: 'YKEY',
    sequence: 'AB',
    description: 'Yellow keycard',
    kind: ThingKind.Key,
  },
  SPIDER_MASTERMIND: {
    id: 7,
    radius: 128,
    sprite: 'SPID',
    description: 'Spider Mastermind',
    kind: ThingKind.Boss,
  },
  BACKPACK: {
    id: 8,
    radius: 20,
    sprite: 'BPAK',
    sequence: 'A',
    description: 'Backpack',
    kind: ThingKind.Pickup,
  },
  FORMER_SERGEANT: {
    id: 9,
    radius: 20,
    sprite: 'SPOS',
    description: 'Former Human Sergeant',
    kind: ThingKind.Monster,
  },
  BLOODY_MESS1: {
    id: 10,
    radius: 16,
    sprite: 'PLAY',
    sequence: 'W',
    description: 'Bloody mess',
    kind: ThingKind.Decoration,
  },
  DEATHMATCH_START: {
    id: 11,
    radius: 20,
    description: 'Deathmatch start',
    kind: ThingKind.Special,
  },
  BLOODY_MESS2: {
    id: 12,
    radius: 16,
    sprite: 'PLAY',
    sequence: 'W',
    description: 'Bloody mess',
    kind: ThingKind.Decoration,
  },
  RED_KEYCARD: {
    id: 13,
    radius: 20,
    sprite: 'RKEY',
    sequence: 'AB',
    description: 'Red keycard',
    kind: ThingKind.Key,
  },
  TELEPORT_LANDING: {
    id: 14,
    radius: 20,
    description: 'Teleport landing',
    kind: ThingKind.Special,
  },
  DEAD_PLAYER: {
    id: 15,
    radius: 16,
    sprite: 'PLAY',
    sequence: 'N',
    description: 'Dead player',
    kind: ThingKind.Decoration,
  },
  CYBERDEMON: {
    id: 16,
    radius: 40,
    sprite: 'CYBR',
    description: 'Cyberdemon',
    kind: ThingKind.Boss,
  },
  CELL_PACK: {
    id: 17,
    radius: 20,
    sprite: 'CELP',
    sequence: 'A',
    description: 'Cell charge pack',
    kind: ThingKind.Pickup,
  },
  DEAD_ZOMBIEMAN: {
    id: 18,
    radius: 20,
    sprite: 'POSS',
    sequence: 'L',
    description: 'Dead former human',
    kind: ThingKind.Decoration,
  },
  DEAD_SERGEANT: {
    id: 19,
    radius: 20,
    sprite: 'SPOSA',
    sequence: 'L',
    description: 'Dead former sergeant',
    kind: ThingKind.Decoration,
  },
  DEAD_IMP: {
    id: 20,
    radius: 20,
    sprite: 'TROO',
    sequence: 'M',
    description: 'Dead imp',
    kind: ThingKind.Decoration,
  },
  DEAD_DEMON: {
    id: 21,
    radius: 30,
    sprite: 'SARG',
    sequence: 'N',
    description: 'Dead demon',
    kind: ThingKind.Decoration,
  },
  DEAD_CACODEMON: {
    id: 22,
    radius: 31,
    sprite: 'HEAD',
    sequence: 'L',
    description: 'Dead cacodemon',
    kind: ThingKind.Decoration,
  },
  DEAD_LOST_SOUL: {
    id: 23,
    radius: 16,
    sprite: 'SKUL',
    sequence: 'K',
    description: 'Dead lost soul (invisible)',
    kind: ThingKind.Decoration,
  },
  BLOOD_POOL1: {
    id: 24,
    radius: 16,
    sprite: 'POL5',
    sequence: 'A',
    description: 'Pool of blood and flesh',
    kind: ThingKind.Decoration,
  },
  IMPALED_HUMAN: {
    id: 25,
    radius: 16,
    sprite: 'POL1',
    sequence: 'A',
    description: 'Impaled human',
    kind: ThingKind.Decoration,
  },
  TWITCHING_IMPALED: {
    id: 26,
    radius: 16,
    sprite: 'POL6',
    sequence: 'AB',
    description: 'Twitching impaled human',
    kind: ThingKind.Decoration,
  },
  SKULL_ON_STICK: {
    id: 27,
    radius: 16,
    sprite: 'POL4',
    sequence: 'A',
    description: 'Skull on a pole',
    kind: ThingKind.Decoration,
  },
  FIVE_SKULLS: {
    id: 28,
    radius: 16,
    sprite: 'POL2',
    sequence: 'A',
    description: 'Five skulls "shish kebab"',
    kind: ThingKind.Decoration,
  },
  SKULLS_AND_CANDLES: {
    id: 29,
    radius: 16,
    sprite: 'POL3',
    sequence: 'AB',
    description: 'Pile of skulls and candles',
    kind: ThingKind.Decoration,
  },
  TALL_GREEN_PILLAR: {
    id: 30,
    radius: 16,
    sprite: 'COL1',
    sequence: 'A',
    description: 'Tall green pillar',
    kind: ThingKind.Decoration,
  },
  SHORT_GREEN_PILLAR: {
    id: 31,
    radius: 16,
    sprite: 'COL2',
    sequence: 'A',
    description: 'Short green pillar',
    kind: ThingKind.Decoration,
  },
  TALL_RED_PILLAR: {
    id: 32,
    radius: 16,
    sprite: 'COL3',
    sequence: 'A',
    description: 'Tall red pillar',
    kind: ThingKind.Decoration,
  },
  SHORT_RED_PILLAR: {
    id: 33,
    radius: 16,
    sprite: 'COL4',
    sequence: 'A',
    description: 'Short red pillar',
    kind: ThingKind.Decoration,
  },
  CANDLE: {
    id: 34,
    radius: 16,
    sprite: 'CAND',
    sequence: 'A',
    description: 'Candle',
    kind: ThingKind.Decoration,
  },
  CANDELABRA: {
    id: 35,
    radius: 16,
    sprite: 'CBRA',
    sequence: 'A',
    description: 'Candelabra',
    kind: ThingKind.Decoration,
  },
  HEART_COLUMN: {
    id: 36,
    radius: 16,
    sprite: 'COL5',
    sequence: 'AB',
    description: 'Short green pillar with beating heart',
    kind: ThingKind.Decoration,
  },
  SKULL_COLUMN: {
    id: 37,
    radius: 16,
    sprite: 'COL6',
    sequence: 'A',
    description: 'Short red pillar with skull',
    kind: ThingKind.Decoration,
  },
  RED_SKULL_KEY: {
    id: 38,
    radius: 20,
    sprite: 'RSKU',
    sequence: 'AB',
    description: 'Red skull key',
    kind: ThingKind.Key,
  },
  YELLOW_SKULL_KEY: {
    id: 39,
    radius: 20,
    sprite: 'YSKU',
    sequence: 'AB',
    description: 'Yellow skull key',
    kind: ThingKind.Key,
  },
  BLUE_SKULL_KEY: {
    id: 40,
    radius: 20,
    sprite: 'BSKU',
    sequence: 'AB',
    description: 'Blue skull key',
    kind: ThingKind.Key,
  },
  EVILEYE: {
    id: 41,
    radius: 16,
    sprite: 'CEYE',
    sequence: 'ABCB',
    description: 'Evil eye',
    kind: ThingKind.Decoration,
  },
  FLOATING_SKULL: {
    id: 42,
    radius: 16,
    sprite: 'FSKU',
    sequence: 'ABC',
    description: 'Floating skull',
    kind: ThingKind.Decoration,
  },
  BURNT_TREE: {
    id: 43,
    radius: 16,
    sprite: 'TRE1',
    sequence: 'A',
    description: 'Burnt tree',
    kind: ThingKind.Decoration,
  },
  TALL_BLUE_FIRESTICK: {
    id: 44,
    radius: 16,
    sprite: 'TBLU',
    sequence: 'ABCD',
    description: 'Tall blue firestick',
    kind: ThingKind.Decoration,
  },
  TALL_GREEN_FIRESTICK: {
    id: 45,
    radius: 16,
    sprite: 'TGRN',
    sequence: 'ABCD',
    description: 'Tall green firestick',
    kind: ThingKind.Decoration,
  },
  TALL_RED_FIRESTICK: {
    id: 46,
    radius: 16,
    sprite: 'TRED',
    sequence: 'ABCD',
    description: 'Tall red firestick',
    kind: ThingKind.Decoration,
  },
  STALAGMITE: {
    id: 47,
    radius: 16,
    sprite: 'SMIT',
    sequence: 'A',
    description: 'Stalagmite',
    kind: ThingKind.Decoration,
  },
  TECH_PILLAR: {
    id: 48,
    radius: 16,
    sprite: 'ELEC',
    sequence: 'A',
    description: 'Tall techno pillar',
    kind: ThingKind.Decoration,
  },
  HANGING_TWITCHING: {
    id: 49,
    radius: 16,
    sprite: 'GOR1',
    sequence: 'ABCB',
    description: 'Hanging victim, twitching',
    kind: ThingKind.Decoration,
    isFloater: true,
  },
  HANGING_ARMS_OUT: {
    id: 50,
    radius: 16,
    sprite: 'GOR2',
    sequence: 'A',
    description: 'Hanging victim, arms out',
    kind: ThingKind.Decoration,
    isFloater: true,
  },
  HANGING_ONE_LEGGED: {
    id: 51,
    radius: 16,
    sprite: 'GOR3',
    sequence: 'A',
    description: 'Hanging victim, one-legged',
    kind: ThingKind.Decoration,
    isFloater: true,
  },
  HANGING_PAIR_OF_LEGS: {
    id: 52,
    radius: 16,
    sprite: 'GOR4',
    sequence: 'A',
    description: 'Hanging pair of legs',
    kind: ThingKind.Decoration,
    isFloater: true,
  },
  HANGING_LEG: {
    id: 53,
    radius: 16,
    sprite: 'GOR5',
    sequence: 'A',
    description: 'Hanging leg',
    kind: ThingKind.Decoration,
    isFloater: true,
  },
  LARGE_BROWN_TREE: {
    id: 54,
    radius: 32,
    sprite: 'TRE2',
    sequence: 'A',
    description: 'Large brown tree',
    kind: ThingKind.Decoration,
  },
  SHORT_BLUE_FIRESTICK: {
    id: 55,
    radius: 16,
    sprite: 'SMBT',
    sequence: 'ABCD',
    description: 'Short blue firestick',
    kind: ThingKind.Decoration,
  },
  SHORT_GREEN_FIRESTICK: {
    id: 56,
    radius: 16,
    sprite: 'SMGT',
    sequence: 'ABCD',
    description: 'Short green firestick',
    kind: ThingKind.Decoration,
  },
  SHORT_RED_FIRESTICK: {
    id: 57,
    radius: 16,
    sprite: 'SMRT',
    sequence: 'ABCD',
    description: 'Short red firestick',
    kind: ThingKind.Decoration,
  },
  SPECTRE: { id: 58, radius: 30, sprite: 'SARG', description: 'Spectre', kind: ThingKind.Monster },
  HANGING_ARMS_OUT_ALT: {
    id: 59,
    radius: 16,
    sprite: 'GOR2',
    sequence: 'A',
    description: 'Hanging victim, arms out (alt)',
    kind: ThingKind.Decoration,
    isFloater: true,
  },
  HANGING_PAIR_OF_LEGS_ALT: {
    id: 60,
    radius: 16,
    sprite: 'GOR4',
    sequence: 'A',
    description: 'Hanging pair of legs (alt)',
    kind: ThingKind.Decoration,
    isFloater: true,
  },
  HANGING_ONE_LEGGED_ALT: {
    id: 61,
    radius: 16,
    sprite: 'GOR3',
    sequence: 'A',
    description: 'Hanging victim, one-legged (alt)',
    kind: ThingKind.Decoration,
    isFloater: true,
  },
  HANGING_LEG_ALT: {
    id: 62,
    radius: 16,
    sprite: 'GOR5',
    sequence: 'A',
    description: 'Hanging leg (alt)',
    kind: ThingKind.Decoration,
    isFloater: true,
  },
  HANGING_TWITCHING_ALT: {
    id: 63,
    radius: 16,
    sprite: 'GOR1',
    sequence: 'ABCB',
    description: 'Hanging victim, twitching (alt)',
    kind: ThingKind.Decoration,
    isFloater: true,
  },
  ARCH_VILE: {
    id: 64,
    radius: 20,
    sprite: 'VILE',
    description: 'Arch-Vile',
    kind: ThingKind.Monster,
  },
  CHAINGUNNER: {
    id: 65,
    radius: 20,
    sprite: 'CPOS',
    description: 'Chaingunner',
    kind: ThingKind.Monster,
  },
  REVENANT: {
    id: 66,
    radius: 20,
    sprite: 'SKEL',
    description: 'Revenant',
    kind: ThingKind.Monster,
  },
  MANCUBUS: {
    id: 67,
    radius: 48,
    sprite: 'FATT',
    description: 'Mancubus',
    kind: ThingKind.Monster,
  },
  ARACHNOTRON: {
    id: 68,
    radius: 64,
    sprite: 'BSPI',
    description: 'Arachnotron',
    kind: ThingKind.Monster,
  },
  HELL_KNIGHT: {
    id: 69,
    radius: 24,
    sprite: 'BOS2',
    description: 'Hell Knight',
    kind: ThingKind.Monster,
  },
  BURNING_BARREL: {
    id: 70,
    radius: 10,
    sprite: 'FCAN',
    sequence: 'ABC',
    description: 'Burning barrel',
    kind: ThingKind.Decoration,
  },
  PAIN_ELEMENTAL: {
    id: 71,
    radius: 31,
    sprite: 'PAIN',
    description: 'Pain Elemental',
    kind: ThingKind.Monster,
    isFloater: true,
  },
  COMMANDER_KEEN: {
    id: 72,
    radius: 16,
    sprite: 'KEEN',
    sequence: 'A',
    description: 'Commander Keen',
    kind: ThingKind.Monster,
  },
  HANGING_GUTS_REMOVED: {
    id: 73,
    radius: 16,
    sprite: 'HDB1',
    sequence: 'A',
    description: 'Hanging victim, guts removed',
    kind: ThingKind.Decoration,
  },
  HANGING_NO_BRAIN: {
    id: 74,
    radius: 16,
    sprite: 'HDB2',
    sequence: 'A',
    description: 'Hanging victim, guts and brain removed',
    kind: ThingKind.Decoration,
    isFloater: true,
  },
  HANGING_TORSO_LOOKING_DOWN: {
    id: 75,
    radius: 16,
    sprite: 'HDB3',
    sequence: 'A',
    description: 'Hanging torso, looking down',
    kind: ThingKind.Decoration,
    isFloater: true,
  },
  HANGING_TORSO_OPEN_SKULL: {
    id: 76,
    radius: 16,
    sprite: 'HDB4',
    sequence: 'A',
    description: 'Hanging torso, open skull',
    kind: ThingKind.Decoration,
    isFloater: true,
  },
  HANGING_TORSO_LOOKING_UP: {
    id: 77,
    radius: 16,
    sprite: 'HDB5',
    sequence: 'A',
    description: 'Hanging torso, looking up',
    kind: ThingKind.Decoration,
    isFloater: true,
  },
  HANGING_TORSO_NO_BRAIN: {
    id: 78,
    radius: 16,
    sprite: 'HDB6',
    sequence: 'A',
    description: 'Hanging torso, brain removed',
    kind: ThingKind.Decoration,
    isFloater: true,
  },
  POOL_OF_BLOOD: {
    id: 79,
    radius: 16,
    sprite: 'POB1',
    sequence: 'A',
    description: 'Pool of blood',
    kind: ThingKind.Decoration,
  },
  POOL_OF_BLOOD_ALT: {
    id: 80,
    radius: 16,
    sprite: 'POB2',
    sequence: 'A',
    description: 'Pool of blood (alt)',
    kind: ThingKind.Decoration,
  },
  POOL_OF_BRAINS: {
    id: 81,
    radius: 16,
    sprite: 'BRS1',
    sequence: 'A',
    description: 'Pool of brains',
    kind: ThingKind.Decoration,
  },
  SUPER_SHOTGUN: {
    id: 82,
    radius: 20,
    sprite: 'SGN2',
    sequence: 'A',
    description: 'Super shotgun',
    kind: ThingKind.Weapon,
  },
  MEGASPHERE: {
    id: 83,
    radius: 20,
    sprite: 'MEGA',
    sequence: 'ABCD',
    description: 'Megasphere',
    kind: ThingKind.Artifact,
  },
  WOLFENSTEIN_SS: {
    id: 84,
    radius: 20,
    sprite: 'SSWV',
    description: 'Wolfenstein SS',
    kind: ThingKind.Monster,
  },
  TALL_TECH_LAMP: {
    id: 85,
    radius: 16,
    sprite: 'TLMP',
    sequence: 'ABCD',
    description: 'Tall techno floor lamp',
    kind: ThingKind.Decoration,
  },
  SHORT_TECH_LAMP: {
    id: 86,
    radius: 16,
    sprite: 'TLP2',
    sequence: 'ABCD',
    description: 'Short techno floor lamp',
    kind: ThingKind.Decoration,
  },
  SPAWN_SPOT: { id: 87, radius: 0, description: 'Spawn spot', kind: ThingKind.Special },
  BOSS_BRAIN: {
    id: 88,
    radius: 16,
    sprite: 'BBRN',
    description: 'Boss Brain',
    kind: ThingKind.Decoration,
  },
  SPAWN_SHOOTER: { id: 89, radius: 20, description: 'Spawn shooter', kind: ThingKind.Special },
  SHOTGUN: {
    id: 2001,
    radius: 20,
    sprite: 'SHOT',
    sequence: 'A',
    description: 'Shotgun',
    kind: ThingKind.Weapon,
  },
  CHAINGUN: {
    id: 2002,
    radius: 20,
    sprite: 'MGUN',
    sequence: 'A',
    description: 'Chaingun',
    kind: ThingKind.Weapon,
  },
  ROCKET_LAUNCHER: {
    id: 2003,
    radius: 20,
    sprite: 'LAUN',
    sequence: 'A',
    description: 'Rocket launcher',
    kind: ThingKind.Weapon,
  },
  PLASMA_RIFLE: {
    id: 2004,
    radius: 20,
    sprite: 'PLAS',
    sequence: 'A',
    description: 'Plasma rifle',
    kind: ThingKind.Weapon,
  },
  CHAINSAW: {
    id: 2005,
    radius: 20,
    sprite: 'CSAW',
    sequence: 'A',
    description: 'Chainsaw',
    kind: ThingKind.Weapon,
  },
  BFG9000: {
    id: 2006,
    radius: 20,
    sprite: 'BFUG',
    sequence: 'A',
    description: 'BFG 9000',
    kind: ThingKind.Weapon,
  },
  AMMO_CLIP: {
    id: 2007,
    radius: 20,
    sprite: 'CLIP',
    sequence: 'A',
    description: 'Ammo clip',
    kind: ThingKind.Pickup,
  },
  SHOTGUN_SHELLS: {
    id: 2008,
    radius: 20,
    sprite: 'SHEL',
    sequence: 'A',
    description: 'Shotgun shells',
    kind: ThingKind.Pickup,
  },
  ROCKET: {
    id: 2010,
    radius: 20,
    sprite: 'ROCK',
    sequence: 'A',
    description: 'Rocket',
    kind: ThingKind.Pickup,
  },
  STIMPACK: {
    id: 2011,
    radius: 20,
    sprite: 'STIM',
    sequence: 'A',
    description: 'Stimpack',
    kind: ThingKind.Pickup,
  },
  MEDIKIT: {
    id: 2012,
    radius: 20,
    sprite: 'MEDI',
    sequence: 'A',
    description: 'Medikit',
    kind: ThingKind.Pickup,
  },
  SOUL_SPHERE: {
    id: 2013,
    radius: 20,
    sprite: 'SOUL',
    sequence: 'ABCDCB',
    description: 'Soul sphere',
    kind: ThingKind.Powerup,
  },
  HEALTH_BONUS: {
    id: 2014,
    radius: 20,
    sprite: 'BON1',
    sequence: 'ABCDCB',
    description: 'Health potion',
    kind: ThingKind.Powerup,
  },
  ARMOR_BONUS: {
    id: 2015,
    radius: 20,
    sprite: 'BON2',
    sequence: 'ABCDCB',
    description: 'Spiritual armor',
    kind: ThingKind.Powerup,
  },
  GREEN_ARMOR: {
    id: 2018,
    radius: 20,
    sprite: 'ARM1',
    sequence: 'AB',
    description: 'Green armor',
    kind: ThingKind.Pickup,
  },
  BLUE_ARMOR: {
    id: 2019,
    radius: 20,
    sprite: 'ARM2',
    sequence: 'AB',
    description: 'Blue armor',
    kind: ThingKind.Pickup,
  },
  INVULNERABILITY: {
    id: 2022,
    radius: 20,
    sprite: 'PINV',
    sequence: 'ABCD',
    description: 'Invulnerability',
    kind: ThingKind.Powerup,
  },
  BERSERK: {
    id: 2023,
    radius: 20,
    sprite: 'PSTR',
    sequence: 'A',
    description: 'Berserk',
    kind: ThingKind.Powerup,
  },
  INVISIBILITY: {
    id: 2024,
    radius: 20,
    sprite: 'PINS',
    sequence: 'BCD',
    description: 'Invisibility',
    kind: ThingKind.Powerup,
  },
  RADIATION_SUIT: {
    id: 2025,
    radius: 20,
    sprite: 'SUIT',
    sequence: 'A',
    description: 'Radiation suit',
    kind: ThingKind.Powerup,
  },
  COMPUTER_MAP: {
    id: 2026,
    radius: 20,
    sprite: 'PMAP',
    sequence: 'ABCDCB',
    description: 'Computer map',
    kind: ThingKind.Powerup,
  },
  FLOOR_LAMP: {
    id: 2028,
    radius: 16,
    sprite: 'COLU',
    sequence: 'A',
    description: 'Floor lamp',
    kind: ThingKind.Decoration,
  },
  BARREL: {
    id: 2035,
    radius: 10,
    sprite: 'BAR1',
    sequence: 'AB',
    description: 'Barrel',
    kind: ThingKind.Barrel,
  },
  LIGHT_AMP: {
    id: 2045,
    radius: 20,
    sprite: 'PVIS',
    sequence: 'AB',
    description: 'Light amplification visor',
    kind: ThingKind.Powerup,
  },
  ROCKET_BOX: {
    id: 2046,
    radius: 20,
    sprite: 'BROK',
    sequence: 'A',
    description: 'Box of rockets',
    kind: ThingKind.Pickup,
  },
  CELL: {
    id: 2047,
    radius: 20,
    sprite: 'CELL',
    sequence: 'A',
    description: 'Cell charge',
    kind: ThingKind.Pickup,
  },
  BULLETS_BOX: {
    id: 2048,
    radius: 20,
    sprite: 'AMMO',
    sequence: 'A',
    description: 'Box of ammo',
    kind: ThingKind.Pickup,
  },
  SHELLS_BOX: {
    id: 2049,
    radius: 20,
    sprite: 'SBOX',
    sequence: 'A',
    description: 'Box of shells',
    kind: ThingKind.Pickup,
  },
  IMP: { id: 3001, radius: 20, sprite: 'TROO', description: 'Imp', kind: ThingKind.Monster },
  DEMON: { id: 3002, radius: 30, sprite: 'SARG', description: 'Demon', kind: ThingKind.Monster },
  BARON_OF_HELL: {
    id: 3003,
    radius: 24,
    sprite: 'BOSS',
    description: 'Baron of Hell',
    kind: ThingKind.Monster,
  },
  ZOMBIEMAN: {
    id: 3004,
    radius: 20,
    sprite: 'POSS',
    description: 'Former Human Trooper',
    kind: ThingKind.Monster,
  },
  CACODEMON: {
    id: 3005,
    radius: 31,
    sprite: 'HEAD',
    description: 'Cacodemon',
    kind: ThingKind.Monster,
    isFloater: true,
  },
  LOST_SOUL: {
    id: 3006,
    radius: 16,
    sprite: 'SKUL',
    description: 'Lost Soul',
    kind: ThingKind.Monster,
    isFloater: true,
  },

  SPIDERDEMON_PROJECTILE: {
    id: 5001,
    radius: 10,
    sprite: 'BAL1',
    description: 'Spiderdemon Projectile',
    kind: ThingKind.Projectile,
  },
  CACODEMON_FIREBALL: {
    id: 5002,
    radius: 6,
    sprite: 'BAL2',
    description: 'Cacodemon Fireball',
    kind: ThingKind.Projectile,
  },
  BARON_BALL: {
    id: 5004,
    radius: 6,
    sprite: 'BAL7',
    description: 'Baron Ball',
    kind: ThingKind.Projectile,
  },
  PLASMA_BOLT: {
    id: 5005,
    radius: 13,
    sprite: 'PLSS',
    description: 'Plasma Bolt',
    kind: ThingKind.Projectile,
  },
  BFG_BALL: {
    id: 5006,
    radius: 13,
    sprite: 'BFS1',
    description: 'BFG Ball',
    kind: ThingKind.Projectile,
  },
  TELEPORT_FOG: {
    id: 9027,
    radius: 20,
    sprite: 'TFOG',
    description: 'Teleport fog',
    kind: ThingKind.Effect,
  },
  ITEM_RESPAWN: {
    id: 9048,
    radius: 20,
    sprite: 'IFOG',
    description: 'Item Respawn Fog',
    kind: ThingKind.Effect,
  },
};

// @TODO Add projectiles?

export const DOOM_THING_MAP_BY_ID: Record<number, ThingType> = Object.values(DOOM_THING_MAP).reduce(
  (acc, thing) => {
    acc[thing.id] = thing;
    return acc;
  },
  {} as Record<number, ThingType>
);
