/** GZDoom CLI flags shared by native gold capture and browser WASM (Step 2c parity). */
export const GZDOOM_PARITY_CAPTURE_ARGS = [
  // Never pause on focus loss. The native gold capture window loses focus in headless/batch
  // runs, which set pauseext=true and burned GZDoom's "PAUSE" overlay into ref.png — a 2D HUD
  // artifact (not a 3D-render diff) that polluted ~150 playfield px and failed/band-aided maps
  // whose scene was actually pixel-identical. pauseext is only set when i_pauseinbackground is
  // on (s_sound.cpp S_SetSoundPaused), so disabling it keeps every capture unpaused + clean.
  '+i_pauseinbackground',
  '0',
  '+vid_hidpi',
  '0',
  '+vid_fullscreen',
  '0',
  '+vid_defwidth',
  '640',
  '+vid_defheight',
  '480',
  '+vid_rendermode',
  '0',
  '+vid_preferbackend',
  '2',
  '+gl_es',
  '1',
  '+r_dynlights',
  '0',
  '+r_drawplayersprites',
  '0',
  '+r_multithreaded',
  '0',
  '+gl_multithread',
  '0',
  '+gl_lights',
  '0',
  '-nosound',
  '-windowed',
  '+wipetype',
  '0',
  '+screenblocks',
  '10',
  '+screenshot_quiet',
  '1',
  '+vid_scalemode',
  '0',
  '+vid_scale_linear',
  '0',
  '+gl_texture_filter',
  '0',
  '+gl_lightmode',
  '1',
  '+gl_fogmode',
  '2',
  '+gl_bandedswlight',
  '0',
] as const;
